### ISSUE TITLE
SRD stat blocks rendering with \n instead of newline

### ISSUE THREAD

**Issue by bszonye** [javalent/fantasy-statblocks#148]
I'm using the plugin for the first time on Windows, and I'm seeing `\n` sequences in stat blocks where there should be newlines. In the source data, the newlines are encoded as `\\n`. I'm wondering whether those should be `\n`? Or perhaps those escapes aren't being decoded correctly at display time.

Here's an example with the Cloud Giant stat block. Note the garbled ***Innate Spellcasting*** ability.

![Cloud Giant](https://user-images.githubusercontent.com/5016349/221951868-2f1fadd6-2bc6-4103-bfb5-86a140da4252.png)

**Comment by bszonye** [comment]
Today I've been trying to craft an equivalent statblock with the correct line & paragraph breaks. It looks like the plugin will render _Innate Spellcasting_ on multiple lines if given `\n` characters instead of `\\n` sequences with the backslash escaped. However, I ran into another problem: The plugin doesn't process the text as markdown, so the double-newline becomes a large gap instead of a paragraph break, and it doesn't seem possible to italicize the spell names.

This input:
```
  - name: Innate Spellcasting
    desc: "The giant's innate spellcasting ability is Charisma. It can innately cast the following spells, requiring no material components:\n\nAt will: *detect magic, fog cloud, light*\n3/day each: *feather fall, fly, misty step, telekinesis*\n1/day each: *control weather, gaseous form*"
```
produces this output:
![image](https://user-images.githubusercontent.com/5016349/222934698-3b0e2017-2117-4d0d-927b-a8a2fe272094.png)

**Comment by bszonye** [comment]
The `spells` attribute can create the italicized lists, but it doesn't appear possible to change the trait name from ***Spellcasting*** to ***Innate Spellcasting.***

**Comment by sigrunixia** [comment]
Hi @bszonye 

I recall this issue and believe it has been fixed, but before closing this as a part of cleanup, I wanted to make sure you were not still having issues?

Also, for italics, we recommend using underscores `_` instead of `*` asterisks because YAML treats asterisks differently than markdown does. This will be notated in updated documentation.

**Comment by bszonye** [comment]
I just updated the plugin, and I am still seeing the problem with `\n` appearing in statblocks like the Cloud Giant. Also, after updating, I'm no longer seeing italicized spell names with the built-in *Spellcasting* trait. The Androsphinx statblock demonstrates both problems. Here are some screenshots taken with the default Obsidian theme.

No spell italics:
![image](https://user-images.githubusercontent.com/5016349/231778016-6397675b-43bc-45f6-8b96-7c72a602106b.png)

Escape characters visible in the stat block:
![image](https://user-images.githubusercontent.com/5016349/231778196-ccd19182-204f-49c0-9c76-207b491d59e7.png)

I tried changing from `*` to `_` in the stat block above, and it also produces a literal `_` character instead of italics.

**Comment by sigrunixia** [comment]
Can you upload a copy of your edited layout, as well as a full copy of your cloud giant render for us to some test please? To ensure the configuration we are looking at is the same. On Apr 13, 2023, at 08:47, Bradd Szonye ***@***.***> wrote:﻿
I just updated the plugin, and I am still seeing the problem with \n appearing in statblocks like the Cloud Giant. Also, after updating, I'm no longer seeing italicized spell names with the built-in Spellcasting trait. The Androsphinx statblock demonstrates both problems. Here are some screenshots taken with the default Obsidian theme.
No spell italics:

Escape characters visible in the stat block:

I tried changing from * to _ in the stat block above, and it also produces a literal _ character instead of italics.

**Comment by bszonye** [comment]
Sure thing. I also reinstalled the plugin fresh to make sure that I didn't have any weird state.

This is my Cloud Giant configuration and how it renders:

    ```statblock
    monster: Cloud Giant
    ```

![image](https://user-images.githubusercontent.com/5016349/231926805-949cfad5-88a7-4ed0-b91d-3c832e0d6521.png)

**Comment by bszonye** [comment]
And this is my attempt at manually formatting the spellcasting block:

    ```statblock
    image: [[Ice Witch.jpg]]
    name: Short Example
    size: Size
    type: type
    subtype: (subtype)
    alignment: alignment
    ac: 10
    hp: 100
    hit_dice: 20d10
    speed: 30 ft.
    stats: [10, 10, 10, 10, 10, 10, 10]
    cr: 1
    spells:
      - "The giant's innate spellcasting ability is Charisma. It can innately cast the following spells, requiring no material components:"
      - At will: detect magic, fog cloud, light
      - 3/day each: feather fall, fly, misty step, telekinesis
      - 1/day each: control weather, gaseous form
    traits:
      - name: Innate Spellcasting
        desc: "The giant's innate spellcasting ability is Charisma. It can innately cast the following spells, requiring no material components:"
      - desc: "At will: _detect magic, fog cloud, light_\n3/day each: _feather fall, fly, misty step, telekinesis_\n1/day each: _control weather, gaseous form_"
    ```
![image](https://user-images.githubusercontent.com/5016349/231927959-6dd4f098-761e-44be-8a28-4974d7ffcb38.png)

Expected: spell names appear in italics in both blocks
Actual: manualy-formatted block has visible `_` characters, neither block has italics

**Comment by sigrunixia** [comment]
@valentine195 I did some testing and there is something happening here. Results below.

- Render as Markdown Enabled on Spells and Traits on default 5e
- Render Links enabled

## Example 1 - Remove Traits
If: 
```yaml
spells:
 - "The giant's innate spellcasting ability is Charisma. It can innately cast the following spells, requiring no material components:"
 - At will: detect magic, fog cloud, light
 - 3/day each: feather fall, fly, misty step, telekinesis
 - 1/day each: control weather, gaseous form
```

Then:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/68425372/232135758-57275c62-e5e2-47de-bfad-ad0e33cfe5ed.png">

- [ ] Spells failing to render as links on their own here
- [ ] All 3 spell lines showing up

## Example 2 - Remove Spells
If: 
```yaml
traits:
  - name: Innate Spellcasting
    desc: "The giant's innate spellcasting ability is Charisma. It can innately cast the following spells, requiring no material components:"
  - name: "At will:"
    desc: "_[[detect magic]]_, _[[fog cloud]]_, _[[light]]_"
  - name: "3/day each:"
    desc: "_[[feather fall]]_, _[[fly]]_, _[[misty step]]_, _[[telekinesis]]_"
  - name: "1/day each:"
    desc: "_[[control weather]]_, _[[gaseous form]]_"
```

Then:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/68425372/232136888-da1caf3c-1e98-4890-9019-8272eefefdea.png">

- [ ] Appears on Point!

P.s., How about css snippet of make links italic within Statblocks automatically? It's so tedious to do it with markdown... 

I shall do that on next iteration of Pathfinder Statblocks. Maybe I should just code that into 5e as well?

```css
.statblock.basic-5e-layout a {
  font-style: italic;
}
```

## Example 3
If:
```yaml
spells:
 - "The giant's innate spellcasting ability is Charisma. It can innately cast the following spells, requiring no material components:"
 - At will: detect magic, fog cloud, light
 - 3/day each: feather fall, fly, misty step, telekinesis
 - 1/day each: control weather, gaseous form
traits:
  - name: Innate Spellcasting
    desc: "The giant's innate spellcasting ability is Charisma. It can innately cast the following spells, requiring no material components:"
  - name: "At will:"
    desc: "[[detect magic]], [[fog cloud]], [[light]]"
  - name: "3/day each:"
    desc: "[[feather fall]], [[fly]], [[misty step]], [[telekinesis]]"
  - name: "1/day each:"
    desc: "[[control weather]], [[gaseous form]]"
```

Then:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/68425372/232137750-5ea39462-f1d1-4fc8-93ff-2b3e084fcca1.png">

- [ ] Wikilinks created in Traits are moved to spell links
- [ ] Traits loses its wikilinks
- [ ] Descriptions between Traits and Links are Switched

So there is something happening here as far as _this_ process. My **guess** is two-fold.
1. With the initial failure to link spells, something was preventing it from linking in the first place.
2. Once linked, it could not handle duplicate data found within trait's block. 

I'll make a separate comment for the SRD entry since I have to go check that out now and I may be able to fix it. :)
