### ISSUE TITLE
Short paragraphs misplaced with Markdown rendering enabled

### ISSUE THREAD

**Issue by bszonye** [javalent/fantasy-statblocks#176]
While troubleshooting #148, I noticed some strange behavior around paragraph breaks.

When:
- [x] markdown rendering is enabled
- [x] an item contains a `\n\n` paragraph break
- [x] the following paragraph is short enough to fit on the previous line

then the paragraph break appears in the wrong place. Example:

    ```statblock
    name: Weird Wrapping Example
    traits:
      - name: Weird wrapping 1
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. The paragraph break should be immediately after the comma,\n\nbut it isn't."
      - name: Weird wrapping 2
        desc: "The paragraph break should be immediately after the comma,\n\nand this time it is! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    ```

![image](https://user-images.githubusercontent.com/5016349/232684633-fc0894e4-3a95-4f2f-afe5-f485aebfed09.png)

I suspect that this is a consequence of the way that the CSS merges the name heading and description into a single block, although it happens regardless of whether the item has a name attribute.

**Comment by sigrunixia** [comment]
Can you confirm if this still happens with the new traits nesting feature?

Nested traits are:

```yaml
traits:
  - name: Weird wrapping 1
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do ei"
    traits:
... and so on
```

**Comment by bszonye** [comment]
Could you please provide a complete example that you want me to test? I've tried a few different things and can't figure out the syntax for nested traits, so I'm not getting a renderable statblock at all.

**Comment by sigrunixia** [comment]
Sorry about that. Apparently a fix needed to go in as well! 
Here is the code.

````yaml
```statblock
layout: Basic 5e Layout
monster: Adult Bronze Dragon
traits+:
  - name: Actionate
    desc: "I am an action"
    traits:
      - name: "Nested Actionate"
        desc: "I am a nested action"
```
````

<img width="446" alt="image" src="https://user-images.githubusercontent.com/68425372/233480456-40313cf7-9d18-4cc7-af40-a7f339f82f32.png">

... Yes I know its not an action. >_>
