### ISSUE TITLE
Support variant spellcasting traits for D&D 5e

### ISSUE THREAD

**Issue by bszonye** [javalent/fantasy-statblocks#198]
D&D5e has a few traits that use the ***Spellcasting*** template but with a different heading, like ***Innate Spellcasting.*** Please provide a way to write these traits without manually recreating the entire layout. (See #148 for background on this request.)

**Comment by sigrunixia** [comment]
Armed with my trusty beginner typescript book, I am thinking we can do something like this. Granted, my syntax is going to be way off as I am borrowing existing code. I was also applying this as descriptions, but headers can be done similarly. 

```ts
class SpellsModal extends MarkdownEnabledModal<SpellsItem> {
    buildProperties(el: HTMLDivElement): void {
        new Setting(this.contentEl)
            .setName("Add Spellcasting Description")
            .setDesc(
                "Enable this to add the ability to set a custom description for the spellcasting trait."
            )
            .addToggle((t) => {
                new Setting(el).setName("Link Monster Property").addText((t) =>
                    t.setValue(block.properties[0]).onChange((v) => {
                        block.properties[0] = v as keyof Monster;
                    })
                );
            });
```

Borrowing from existing monster property, it allows the user to specify per spell trait block if they want to set a custom property. That custom property would then be situated at the top of the spell blocks of its linked spell trait.

#### YAML Look
```yaml
linked-property: innate for spellcasting and primal for spells

innate: "__Innate Spellcasting__"
spellcasting:
 - "yadda yadda"
 - "yadda"
primal: "__[[Primal Spellweaving]]__: The Mimic is a Primal Spellweaver and is able to cast the powers of creation. All spells strike three times per cast."
spells:
 - "Yadda"
 - "Yadda"
```

##### Appearance Look
```md
__Innate Spellcasting__
 - yadda yadda
 - yadda


__[[Primal Spellweaving]]__
The Mimic is a Primal Spellweaver and is able to cast the powers of creation. All spells strike three times per cast.
 - Yadda
 - Yadda
```

Sadly it would still require a slight amount of layout editing, but I think that is unavoidable.
