### ISSUE TITLE
🐞 YOUR TITLE HERE

### ISSUE THREAD

**Issue by EroSanin** [javalent/fantasy-statblocks#321]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

```statblock
columnHeight: 600
```
Reduces length of left column to provided max height value

### Current behaviour

First render is showing max length for left column, after reload note it seems working as it should, reducing height of left column.

### Reproduction

1. On WIndows system, Create new vault.
2. Install plugins Fantasy-statblock, Dataview
3. Add template:

[Antagonist.json](https://github.com/javalent/fantasy-statblocks/files/13692956/Antagonist.json)

4. Create note with this image (created by MidJourney)
![anarchistic](https://github.com/javalent/fantasy-statblocks/assets/13541672/a72bd8b7-421b-4bcb-982d-913f73f1db83)

```

---

tag: npc, antagonisci
job:  Anarchiści
imie: Anarchiści
zycie: 6
sila_woli: 6
czlowieczenstwo: 6
moc_krwi: 2


opis: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

atrybut_fizyczna: 3
atrybut_spoleczna: 3
atrybut_umyslowa: 3


umiejetnosc_1_name: "Broń biała"
umiejetnosc_1: 6
umiejetnosc_2_name: "Kradzież"
umiejetnosc_2: 7
umiejetnosc_3_name: "Prowadzenie pojazdów"
umiejetnosc_3: 6
umiejetnosc_4_name: "Strzelanie"
umiejetnosc_4: 6
umiejetnosc_5_name: "Sztuka Przetrwania"
umiejetnosc_5: 6
umiejetnosc_6_name: "Walka wręcz "
umiejetnosc_6: 7
umiejetnosc_7_name: "Wysportowanie"
umiejetnosc_7: 7
umiejetnosc_8_name: "Cwaniactwo"
umiejetnosc_8: 7
umiejetnosc_9_name: "Zdolności przywódcze"
umiejetnosc_9: 6

dyscyplina_1_name: Animalizm
dyscyplina_1: 2
dyscyplina_2_name: Odporność
dyscyplina_2: 3
dyscyplina_3_name: Potencja
dyscyplina_3: 2
dyscyplina_4_name: Przyspieszenie
dyscyplina_4: 2
dyscyplina_5_name: Transformacja
dyscyplina_5: 1



---




```statblock
layout: Antagonist
name: Anarchiści
description: "![[anarchistic.png]]"
additional: "`=this.opis`"
columnHeight: 600
attributes:
  - name: 
    desc: "Fizyczne (`=this.atrybut_fizyczna`)"
  - name: 
    desc: "Społeczne (`=this.atrybut_spoleczna`)"
  - name: 
    desc: "Umysłowe (`=this.atrybut_umyslowa`)"
secondary:
  - name: 
    desc: "**Życie** (`=this.zycie`) "
  - name: 
    desc: "**Siła Woli** (`=this.sila_woli`) "
HighDice:
  - name: 
    desc: "`=this.umiejetnosc_1_name` (`=this.umiejetnosc_1`)"
  - name: 
    desc: "`=this.umiejetnosc_2_name` (`=this.umiejetnosc_2`)"
  - name: 
    desc: "`=this.umiejetnosc_3_name` (`=this.umiejetnosc_3`)"
  - name: 
    desc: "`=this.umiejetnosc_4_name` (`=this.umiejetnosc_4`)"
  - name: 
    desc: "`=this.umiejetnosc_5_name` (`=this.umiejetnosc_5`)"
  - name: 
    desc: "`=this.umiejetnosc_6_name` (`=this.umiejetnosc_6`)"
  - name: 
    desc: "`=this.umiejetnosc_7_name` (`=this.umiejetnosc_7`)"
  - name: 
    desc: "`=this.umiejetnosc_8_name` (`=this.umiejetnosc_8`)"
  - name: 
    desc: "`=this.umiejetnosc_9_name` (`=this.umiejetnosc_9`)"
special:
  - name: 
    desc: "**`=this.zdolnosc_1_name`** `=this.zdolnosc_1`"


```

5. Render note. (First time left column will be fully extended)
6. Close and reopen note. It seems fine

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

3.16.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.
