### ISSUE TITLE
🐞 Removing Traits does not seem to work

### ISSUE THREAD

**Issue by dfaggioli** [javalent/fantasy-statblocks#467]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

It should be possible to remove Traits, e.g., if we have:

```statblock
statblock: true
name: umano_comune
extends: creatura
creatura: Umano Comune
ac: 2
hit_dice: 6+1d3
hp: 8
mana: 0
vestiti: "[[Abiti Normali]]"
abilita_razza:
  - name: "[[Lingua delle Lande]]"
  - name: "[[Capacita di Guarigione|Capacità di Guarigione]]"
  - name: TEST
    desc: test
```

And:

```statblock
statblock: true
name: umano_schiavo_gladiatore
monster: umano_comune
creatura: Umano Schiavo-Gladiatore
abilita_razza-:
  - name: TEST
abilita_razza+:
  - name: TEST2
    desc: test2
```

The latter should have, in "abilita_razza": "[[Lingua delle Lande]]", "[[Capacita di Guarigione|Capacità di Guarigione]]" and TEST2

### Current behaviour

After https://github.com/javalent/fantasy-statblocks/commit/12df3838d5e755fa2f5aa66cf3188b3dab7a3754, Traits have improved a lot! In fact, now overriding and adding Traits works fine (for me). What still doesn't work is removing them :-)

In fact, sticking to the example above, "abilita_razza" still has the "TEST"

![image](https://github.com/user-attachments/assets/1eb89e43-1c26-450f-8e19-cf74b0a4ca17)

### Reproduction

Just create a statblock that inherits some Traits (say, "A") from another one (e.g., using `monster:`) and then try to remove any with `A-:`.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.6.7

### Plugin Version

4.7.8

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

**Comment by jameswtelfer** [comment]
I think you have a mistake in your YAML, I came across this issue when wrestling with this feature myself, albeit with a DND5e stat block.

These lines:

```yaml
extends: creatura
creatura: Umano Comune
```

Should be 

```yaml
extends: Umano Comune
```

My working example (Obsidian 1.7.4 / Fantasy Stat Blocks 4.7.8) is this:

```yaml
extends: Deep Gnome (Svirfneblin)
name: Abbot Kavoda
ac: 12
traits-:
  - name: Innate Spellcasting
traits+:
  - name: Innate Spellcasting.
    desc: |
      The gnome’s innate spellcasting ability is Intelligence (spell save DC 11). It can innately cast the following spells, requiring no material components:
      At will: nondetection (self only)
      1/day each: blindness/deafness, blur, disguise self
      3/day each: meld into stone
```
