### ISSUE TITLE
🐞 Import TetraCube Data omits and/or changes Data

### ISSUE THREAD

**Issue by M4leph1st0** [javalent/fantasy-statblocks#476]
### Check for existing bug reports before submitting.

- [x] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Importing a monster not covered by the SRD results in a complete 1:1 conversion of the statblock in question.

### Current behaviour

Data is altered and an incomplete Statblock will be generated.
Using a statblock covered by the SRD does not result in this behavior.

Basically the plugin creates following YAML out of the given .MONSTER file

~~~
image: 
name: Arcane Guardian
source: TetraCube
type: construct
subtype: ""
size: small
alignment: ""
hp: "27"
hit_dice: 6d6 + 6
ac: ""
speed: 0 ft., fly 30 ft. (hover)
stats:
  - "6"
  - "14"
  - "12"
  - "17"
  - "11"
  - "10"
damage_immunities: poison, psychic
damage_resistances: ""
damage_vulnerabilities: ""
condition_immunities: charmed, exhaustion, frightened, paralyzed, poisoned
saves: []
skillsaves:
  - arcana: 5
  - perception: 2
senses: darkvision 60 ft., passive Perception 12
languages: the languages of it's creator
cr: "2"
traits: []
actions:
  - name: Arcane Blast
    desc: "Ranged Spell Attack: +5 to hit, range 60 ft., one target. Hit: 3 (1d6) force damage."
bonus_actions: []
reactions:
  - name: Evasive Maneuvers
    desc: When an Arcane Guardian is targeted by an attack, it can use its reaction to increase its AC by 2 until the start of its next turn.
legendary_description: 
legendary_actions: []
mythic_description: 
mythic_actions: []
lair_description: 
lair_actions: []
lair_description_end: 
regional_description: 
regional_actions: 
regional_description_end: 
~~~

Which ommits the ability score modifier and the whole spellcasting section and modifies the language section as well as the damage of Arcane Blast from 3d6 to 1d6

[arcane guardian.zip](https://github.com/user-attachments/files/18551162/arcane.guardian.zip)

### Reproduction

1. Launch Obsidian
2. Open Settings
3. Navigate to Fantasy Statblocks Setting
4. Use the build in TetraCube importer 
5. Import the .monster file 
6. Check the YAML preview 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [x] Windows

### Obsidian Version Check

1.7.7

### Plugin Version

4.8.1

### Confirmation

- [x] I have disabled all other plugins and the issue still persists.

**Comment by UnavengedAvo** [comment]
I have run into a similar issue when exporting creatures from https://tetra-cube.com/dnd/dnd-statblock.html, it seems as though the AC is not being listed.

I have attached the _.monster_ file and image export for a homebrew creature, and this is what it looks like in Obsidian:
[antwerp.zip](https://github.com/user-attachments/files/20727785/antwerp.zip)
```
image: 
name: Antwerp
source: TetraCube
type: ooze
subtype: ""
size: medium
alignment: unaligned
hp: "71"
hit_dice: 11d8 + 22
ac: ""
speed: 30 ft.
stats:
  - "16"
  - "14"
  - "14"
  - "10"
  - "11"
  - "10"
damage_immunities: bludgeoning, force, necrotic, psychic, radiant; Elemental Damage, Magical Attacks
damage_resistances: ""
damage_vulnerabilities: piercing, slashing
condition_immunities: ""
saves: []
skillsaves:
  - acrobatics: 4
  - athletics: 5
senses: darkvision 60 ft., passive Perception 10
languages: "&mdash;"
cr: "3"
traits:
  - name: Standing Leap
    desc: The antwerp's long jump is up to 15 feet and its high jump is up to 30 feet, with or without a running start.
actions:
  - name: Bump
    desc: "Melee Weapon Attack: +5 to hit, reach 15 ft., one target. Hit: 1 bludgeoning damage. The target creature must succeed on a DC +12 Dexterity saving throw or be knocked prone, unless it is two or more sizes larger than the antwerp."
  - name: Slam
    desc: The antwerp leaps up to 30 feet into the air and slams on to a target creature, which must succeed on a DC +12 Dexterity saving throw or take 2d6 bludgeoning damage for every 10 feet the Antwerp leaped (up to a maximum of 5d6). The impacted creature is also knocked prone, unless it is two or more sizes larger than the antwerp.
legendary_description: 
legendary_actions: 
mythic_description: 
mythic_actions: 
lair_description: 
lair_actions: 
lair_description_end: 
regional_description: 
regional_actions: 
regional_description_end:
```

I also had a similar issue whereby the spells for another creature I created is also not being listed:
[baba yaga.zip](https://github.com/user-attachments/files/20727845/baba.yaga.zip)
```
image: 
name: Baba Yaga
source: TetraCube
type: fey
subtype: any race
size: medium
alignment: chaotic neutral
hp: "189"
hit_dice: 18d8 + 108
ac: ""
speed: 30 ft., fly 40 ft.
stats:
  - "14"
  - "16"
  - "22"
  - "18"
  - "20"
  - "24"
damage_immunities: poison
damage_resistances: cold, fire, lightning; bludgeoning, piercing, and slashing from nonmagical attacks
damage_vulnerabilities: ""
condition_immunities: charmed, frightened, poisoned
saves:
  - constitution: 11
  - wisdom: 10
  - charisma: 12
skillsaves:
  - arcana: 9
  - deception: 12
  - insight: 10
  - perception: 10
  - persuasion: 12
senses: darkvision 120 ft., truesight 60 ft., passive Perception 20
languages: Abyssal, Common and Sylvan
cr: "13"
traits:
  - name: Legendary Resistance (3/day)
    desc: If Baba Yaga fails a saving throw, she can choose to succeed instead.
  - name: Magic Resistance
    desc: Baba Yaga has advantage on saving throws against spells and other magical effects.
actions:
  - name: Multiattack
    desc: Baba Yaga makes two attacks with her magic broom.
  - name: Magic Broom
    desc: "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: +7 bludgeoning damage, and 3 (1d6) force damage."
reactions:
  - name: Protective Magic (3/Day)
    desc: Baba Yaga casts Counterspell or Shield in response to the spell's trigger, using the same spellcasting ability as Spellcasting.
legendary_description: Baba Yaga can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. Baba Yaga regains spent legendary actions at the start of its turn.
legendary_actions:
  - name: Cantrip
    desc: Baba Yaga casts a cantrip.
  - name: "Familiars' Fury (Cost: 2 Actions)"
    desc: Baba Yaga channels her fury through her pets. Both Bats and Scarlet (if still alive) immediately take one action each, empowered by her magic, they gain 3 (1d6) psychic damage on a hit this round.
  - name: "Twist Fate (Cost: 3 Actions)"
    desc: Baba Yaga magically warps probability. She forces a creature that just succeeded on a saving throw, avoided an attack, or rolled a critical hit to reroll the die, taking the new result.
mythic_description: 
mythic_actions: 
lair_description: When Baba Yaga is within her chicken-legged hut, the very structure bends to her will. On initiative count 20 (losing initiative ties), she can use one of the following magical effects
lair_actions:
  - name: Cackle of Madness
    desc: A magical laugh fills the hut. All enemies must succeed on a DC +18 Wisdom saving throw or become frightened until the end of their next turn.
  - name: STAY!
    desc: 'Baba Yaga chants: "Powers of Night, Shadows of Day — Heed now my Words! Henceforth you STAY!"Each creature of her choice within 60 feet must succeed on a DC +18 Wisdom saving throw or become paralyzed. A creature may repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.'
  - name: Dancing Hut
    desc: "Baba Yaga yells out: “Kurochka, we dance! Lift those knees like in the old days!”All creatures on the floor (except Baba Yaga and her chosen creatures) must succeed on a DC +16 Dexterity saving throw or be knocked prone and take 3 (1d6) bludgeoning damage from crashing into floorboards, furniture, or cavern debris. On a success, they remain standing."
lair_description_end: Baba Yaga can't repeat an effect until they have all been used, and she can't use the same effect two rounds in a row.
regional_description: 
regional_actions: 
regional_description_end:

```
